Repository equinor/webviz-core-components, pull requests merged in 2021-09, with the labels that each got.

#161 Bump Dash version to 2.0
  CHANGELOG.md
  setup.py
  tests/test_color_scales.py
  tests/test_graph.py
  tests/test_plugin_placeholder.py
  usage.py
  webviz_core_components/wrapped_components/checklist.py
  webviz_core_components/wrapped_components/collapsive_header.py
  webviz_core_components/wrapped_components/dropdown.py
  webviz_core_components/wrapped_components/flexbox.py
  webviz_core_components/wrapped_components/flexcolumn.py
  webviz_core_components/wrapped_components/frame.py
  webviz_core_components/wrapped_components/graph.py
  webviz_core_components/wrapped_components/header.py
  webviz_core_components/wrapped_components/label.py
  webviz_core_components/wrapped_components/radioitems.py
  webviz_core_components/wrapped_components/range_slider.py
  webviz_core_components/wrapped_components/select_with_label.py
  webviz_core_components/wrapped_components/selectors.py
  webviz_core_components/wrapped_components/slider.py
  webviz_core_components/wrapped_components/tab.py
  webviz_core_components/wrapped_components/tabs.py
Labels: maintenance, next release 🚢

#154 Implemented a new menu component
  .vscode/launch.json
  CHANGELOG.md
  react/package-lock.json
  react/package.json
  react/src/demo/App.tsx
  react/src/lib/components/Menu/Menu.css
  react/src/lib/components/Menu/Menu.tsx
  react/src/lib/components/Menu/components/FilterInput/FilterInput.tsx
  react/src/lib/components/Menu/components/FilterInput/index.ts
  react/src/lib/components/Menu/components/Group/Group.css
  react/src/lib/components/Menu/components/Group/Group.tsx
  react/src/lib/components/Menu/components/Group/index.ts
  react/src/lib/components/Menu/components/Icon/Icon.tsx
  react/src/lib/components/Menu/components/Icon/index.ts
  react/src/lib/components/Menu/components/Logo/Logo.css
  react/src/lib/components/Menu/components/Logo/Logo.tsx
  react/src/lib/components/Menu/components/Logo/index.ts
  react/src/lib/components/Menu/components/MenuBar/MenuBar.css
  react/src/lib/components/Menu/components/MenuBar/MenuBar.tsx
  react/src/lib/components/Menu/components/MenuBar/index.ts
  react/src/lib/components/Menu/components/MenuContent/MenuContent.css
  react/src/lib/components/Menu/components/MenuContent/MenuContent.tsx
  react/src/lib/components/Menu/components/MenuContent/index.ts
  react/src/lib/components/Menu/components/MenuDrawer/MenuDrawer.css
  react/src/lib/components/Menu/components/MenuDrawer/MenuDrawer.tsx
  react/src/lib/components/Menu/components/MenuDrawer/index.ts
  react/src/lib/components/Menu/components/Page/Page.css
  react/src/lib/components/Menu/components/Page/Page.tsx
  react/src/lib/components/Menu/components/Page/index.ts
  react/src/lib/components/Menu/components/Section/Section.css
  react/src/lib/components/Menu/components/Section/Section.tsx
  react/src/lib/components/Menu/components/Section/index.ts
  react/src/lib/components/Menu/components/TopMenu/TopMenu.css
  react/src/lib/components/Menu/components/TopMenu/TopMenu.tsx
  react/src/lib/components/Menu/components/TopMenu/index.ts
  react/src/lib/components/Menu/components/TopMenu/pin.svg
  react/src/lib/components/Menu/components/TopMenu/unpin.svg
  react/src/lib/components/Menu/index.ts
  react/src/lib/components/Menu/types/menu-position.ts
  react/src/lib/components/Menu/types/navigation.ts
  react/src/lib/components/Menu/utils/check-url.ts
  react/src/lib/components/Overlay/Overlay.css
  react/src/lib/components/Overlay/Overlay.tsx
  react/src/lib/components/Overlay/index.ts
  react/src/lib/components/ScrollArea/ScrollArea.css
  react/src/lib/components/ScrollArea/ScrollArea.tsx
  react/src/lib/components/ScrollArea/index.ts
  react/src/lib/components/WebvizPluginPlaceholder/webviz_plugin_component.css
  react/src/lib/hooks/useContainerDimensions.ts
  react/src/lib/hooks/usePan.ts
  react/src/lib/hooks/usePrevious.ts
  react/src/lib/hooks/useScroll.ts
  react/src/lib/hooks/useWindowSize.ts
  react/src/lib/index.ts
  react/src/lib/shared-types/point.ts
  react/src/lib/shared-types/size.ts
  react/src/lib/utils/geometry.ts
Labels: enhancement, next release 🚢

#164 Added touch support
  react/src/lib/components/Menu/components/MenuBar/MenuBar.css
  react/src/lib/components/ScrollArea/ScrollArea.tsx
  react/src/lib/utils/geometry.ts
Labels: enhancement, next release 🚢

#167 Improved transition of menu when closing.
  react/src/lib/components/Menu/Menu.tsx
  react/src/lib/components/Menu/components/Logo/Logo.tsx
  react/src/lib/components/Menu/components/MenuBar/MenuBar.tsx
  react/src/lib/components/Menu/components/MenuDrawer/MenuDrawer.tsx
Labels: next release 🚢
