Repository equinor/webviz-core-components, pull requests merged in 2022-08, with the labels that each got.

#232 Remove unused prop from WebvizView component
  react/src/lib/components/WebvizView/WebvizView.tsx
Labels: bug, enhancement

#231 Bug fix: jumping view carousel icon and non-centered selection popup
  react/src/lib/components/WebvizSettingsDrawer/components/ViewList/view-list.css
  react/src/lib/components/WebvizSettingsDrawer/components/ViewList/view-list.tsx
  react/src/lib/components/WebvizSettingsDrawer/components/ViewSelector/view-selector.css
  react/src/lib/components/WebvizSettingsDrawer/components/ViewSelector/view-selector.tsx
Labels: bug

#234 Adjusted bug in tour component displaying messages outside view
  CHANGELOG.md
  react/src/lib/components/WebvizPluginTour/WebvizPluginTour.tsx
  react/src/lib/components/WebvizPluginTour/webviz-plugin-tour.css
Labels: bug

#230 Create component for view visibility toggle container
  react/src/lib/components/ViewVisibilityContainer/ViewVisibilityContainer.tsx
  react/src/lib/components/ViewVisibilityContainer/index.ts
  react/src/lib/index.ts
Labels: enhancement

#236 Removed usage of `withStyles` in `Dialog` component
  CHANGELOG.md
  react/src/lib/components/Dialog/components/DialogComponent.tsx
  react/src/lib/components/Dialog/components/DraggablePaperComponent.tsx
Labels: bug

#240 `WLF` and `Menu`: Storing of states
  CHANGELOG.md
  react/src/lib/components/Menu/Menu.tsx
  react/src/lib/components/Menu/components/Group/Group.tsx
  react/src/lib/components/Menu/utils/check-url.ts
  react/src/lib/components/WebvizContentManager/WebvizContentManager.tsx
  react/src/lib/components/WebvizPluginTour/WebvizPluginTour.tsx
  react/src/lib/components/WebvizSettings/WebvizSettings.tsx
  react/src/lib/components/WebvizSettingsDrawer/components/PluginActions/plugin-actions.tsx
  react/src/lib/components/WebvizSettingsGroup/WebvizSettingsGroup.tsx
  react/src/lib/components/WebvizSettingsGroup/webviz-settings-group.css
  react/src/lib/components/WebvizViewElement/webviz-view-element.css
Labels: enhancement

#243 Add debounce time for wcc.Select
  react/src/lib/components/Select/Select.stories.tsx
  react/src/lib/components/Select/Select.tsx
Labels: enhancement

#245 Updated changelog for PR #243
  CHANGELOG.md
Labels: enhancement
