Repository equinor/webviz-core-components, pull requests merged in 2022-09, with the labels that each got.

#248 Added missing `id` and `key` props
  CHANGELOG.md
  react/src/lib/components/WebvizSettingsDrawer/components/ViewList/view-list.tsx
  react/src/lib/components/WebvizSettingsGroup/WebvizSettingsGroup.tsx
Labels: enhancement

#247 Settings dialog of view elements can now be controlled via tour steps (WLF)
  react/src/lib/components/WebvizContentManager/WebvizContentManager.tsx
  react/src/lib/components/WebvizPluginTour/WebvizPluginTour.tsx
  react/src/lib/components/WebvizPluginWrapper/WebvizPluginWrapper.tsx
  react/src/lib/components/WebvizViewElement/WebvizViewElement.tsx
  react/src/lib/utils/waitUntilElementIsAvailable.ts
Labels: bug

#252 Refactored `Menu` component to make it work in sync with `dcc.Location`
  CHANGELOG.md
  react/src/demo/App.tsx
  react/src/lib/components/Menu/Menu.stories.tsx
  react/src/lib/components/Menu/Menu.tsx
  react/src/lib/components/Menu/components/Logo/Logo.tsx
  react/src/lib/components/Menu/components/MenuBar/MenuBar.tsx
  react/src/lib/components/Menu/components/MenuContent/MenuContent.tsx
  react/src/lib/components/Menu/components/Page/Page.tsx
Labels: enhancement

#260 Compare view id string and active id in store
  react/src/lib/components/WebvizSettingsDrawer/components/ViewSelector/view-selector.tsx
Labels: bug, enhancement

#257 Add debounce time for wcc.Select with fix after revert
  CHANGELOG.md
  react/src/lib/components/Select/Select.stories.tsx
  react/src/lib/components/Select/Select.tsx
Labels: bug, enhancement

#264 Now shows homepage as first page when given
  react/src/lib/components/Menu/Menu.tsx
Labels: bug, next release 🚢

#267 Adjust ignores for `.vscode` folder in `.gitignore`
  .gitignore
Labels: enhancement
